/* Local demo/fallback data.
   Once Supabase is configured, the live database becomes the source of truth. */
const demoCards = [
  { id: 1, player: "Cooper Flagg", team: "Dallas Mavericks", category: "Basketball", year: "2025-26", set_name: "Panini Prizm Monopoly", card_number: "Rookie", parallel: "Base", condition: "Raw", grade: "—", purchase_price: 600, estimated_value: 600, acquired_date: "2026-01-01", rookie: true, featured: true, image_url: "assets/cards/cooper-flagg.svg", note: "Örnek kayıt." },
  { id: 2, player: "Dylan Harper", team: "San Antonio Spurs", category: "Basketball", year: "2025-26", set_name: "Rookie Card", card_number: "RC", parallel: "Base", condition: "Raw", grade: "—", purchase_price: 277, estimated_value: 277, acquired_date: "2026-01-01", rookie: true, featured: true, image_url: "assets/cards/dylan-harper.svg", note: "Örnek kayıt." },
  { id: 3, player: "Cristiano Ronaldo", team: "Portugal", category: "Football", year: "2024", set_name: "Topps UEFA Euro", card_number: "—", parallel: "Captain Green", condition: "Raw", grade: "—", purchase_price: null, estimated_value: null, acquired_date: "2024-01-01", rookie: false, featured: true, image_url: "assets/cards/ronaldo.svg", note: "Örnek kayıt." },
  { id: 4, player: "Victor Wembanyama", team: "San Antonio Spurs", category: "Basketball", year: "2023-24", set_name: "Rookie Card", card_number: "RC", parallel: "Base", condition: "Raw", grade: "—", purchase_price: null, estimated_value: null, acquired_date: "2024-01-01", rookie: true, featured: true, image_url: "assets/cards/wembanyama.svg", note: "Örnek kayıt." },
  { id: 5, player: "Jude Bellingham", team: "England / Real Madrid", category: "Football", year: "2024", set_name: "Topps Euro", card_number: "—", parallel: "Energy", condition: "Raw", grade: "—", purchase_price: null, estimated_value: null, acquired_date: "2024-01-01", rookie: false, featured: false, image_url: "assets/cards/bellingham.svg", note: "Örnek kayıt." },
  { id: 6, player: "Kobe Bryant", team: "Los Angeles Lakers", category: "Basketball", year: "Modern / Vintage", set_name: "Basketball Card", card_number: "—", parallel: "Base", condition: "Raw", grade: "—", purchase_price: null, estimated_value: null, acquired_date: null, rookie: false, featured: false, image_url: "assets/cards/kobe.svg", note: "Örnek kayıt." }
];
