-- VaultCardstr Collection Growth history
-- Run this once in Supabase SQL Editor.

create table if not exists public.collection_growth_history (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete cascade,
  snapshot_date date not null default current_date,
  total_cards integer not null default 0,
  total_value numeric(14,2) not null default 0,
  value_per_card numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  unique (owner_id, snapshot_date)
);

alter table public.collection_growth_history enable row level security;

drop policy if exists "Public can view collection growth history" on public.collection_growth_history;
create policy "Public can view collection growth history"
on public.collection_growth_history
for select
to anon, authenticated
using (true);

revoke insert, update, delete on public.collection_growth_history from anon;
grant select on public.collection_growth_history to anon, authenticated;
grant insert, update, delete on public.collection_growth_history to authenticated;

drop function if exists public.refresh_collection_growth_snapshot(uuid);

create or replace function public.refresh_collection_growth_snapshot(p_owner_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_total_cards integer;
  v_total_value numeric(14,2);
begin
  select count(*), coalesce(sum(estimated_value), 0)
  into v_total_cards, v_total_value
  from public.cards
  where owner_id = p_owner_id;

  insert into public.collection_growth_history (
    owner_id,
    snapshot_date,
    total_cards,
    total_value,
    value_per_card
  )
  values (
    p_owner_id,
    current_date,
    v_total_cards,
    v_total_value,
    case
      when v_total_cards > 0 then round(v_total_value / v_total_cards, 2)
      else 0
    end
  )
  on conflict (owner_id, snapshot_date)
  do update set
    total_cards = excluded.total_cards,
    total_value = excluded.total_value,
    value_per_card = excluded.value_per_card;
end;
$$;

revoke all on function public.refresh_collection_growth_snapshot(uuid) from public;
grant execute on function public.refresh_collection_growth_snapshot(uuid) to authenticated;

drop function if exists public.handle_collection_growth_snapshot();

create or replace function public.handle_collection_growth_snapshot()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_owner_id uuid;
begin
  v_owner_id := coalesce(new.owner_id, old.owner_id);

  if v_owner_id is not null then
    perform public.refresh_collection_growth_snapshot(v_owner_id);
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists cards_growth_snapshot_after_change on public.cards;
create trigger cards_growth_snapshot_after_change
after insert or update or delete on public.cards
for each row
execute function public.handle_collection_growth_snapshot();
