-- VaultCardstr Community Feed
-- Run this in Supabase SQL Editor before enabling likes/comments.

create table if not exists public.card_likes (
  id bigint generated by default as identity primary key,
  card_id bigint not null references public.cards(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (card_id, user_id)
);

create table if not exists public.card_comments (
  id bigint generated by default as identity primary key,
  card_id bigint not null references public.cards(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

alter table public.card_likes enable row level security;
alter table public.card_comments enable row level security;

drop policy if exists "Public can view card likes" on public.card_likes;
create policy "Public can view card likes" on public.card_likes for select to anon, authenticated using (true);

drop policy if exists "Users can like cards" on public.card_likes;
create policy "Users can like cards" on public.card_likes for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists "Users can remove their likes" on public.card_likes;
create policy "Users can remove their likes" on public.card_likes for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Public can view card comments" on public.card_comments;
create policy "Public can view card comments" on public.card_comments for select to anon, authenticated using (true);

drop policy if exists "Users can add comments" on public.card_comments;
create policy "Users can add comments" on public.card_comments for insert to authenticated with check ((select auth.uid()) = user_id and char_length(body) between 1 and 500);

drop policy if exists "Users can delete their comments" on public.card_comments;
create policy "Users can delete their comments" on public.card_comments for delete to authenticated using ((select auth.uid()) = user_id);

revoke all on public.card_likes from anon, authenticated;
grant select on public.card_likes to anon, authenticated;
grant insert, delete on public.card_likes to authenticated;

revoke all on public.card_comments from anon, authenticated;
grant select on public.card_comments to anon, authenticated;
grant insert, delete on public.card_comments to authenticated;

create index if not exists card_likes_card_id_idx on public.card_likes(card_id);
create index if not exists card_comments_card_id_idx on public.card_comments(card_id);
create index if not exists card_comments_created_at_idx on public.card_comments(created_at desc);
