-- FRENZYGOLDIES / VAULTCARDSTR
-- Run this entire script in Supabase SQL Editor.
-- It creates the cards table, RLS policies and a public card-images bucket.

create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  player text not null,
  team text default '',
  category text not null default 'Football',
  year text default '',
  set_name text default '',
  card_number text default '',
  parallel text default 'Base',
  condition text default 'Raw',
  grade text default '—',
  price text default 'Collection',
  acquired text default '',
  rookie boolean not null default false,
  featured boolean not null default false,
  image_url text not null,
  note text default '',
  created_at timestamptz not null default now()
);

alter table public.cards enable row level security;

drop policy if exists "Public can view cards" on public.cards;
create policy "Public can view cards"
on public.cards
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can add cards" on public.cards;
create policy "Authenticated can add cards"
on public.cards
for insert
to authenticated
with check (true);

drop policy if exists "Authenticated can edit cards" on public.cards;
create policy "Authenticated can edit cards"
on public.cards
for update
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated can delete cards" on public.cards;
create policy "Authenticated can delete cards"
on public.cards
for delete
to authenticated
using (true);

-- Public bucket for displaying card photos.
insert into storage.buckets (id, name, public)
values ('card-images', 'card-images', true)
on conflict (id) do update set public = true;

-- Public can read/download card images.
drop policy if exists "Public can view card images" on storage.objects;
create policy "Public can view card images"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'card-images');

-- Only signed-in users can upload/change/delete card images.
drop policy if exists "Authenticated can upload card images" on storage.objects;
create policy "Authenticated can upload card images"
on storage.objects
for insert
to authenticated
with check (bucket_id = 'card-images');

drop policy if exists "Authenticated can update card images" on storage.objects;
create policy "Authenticated can update card images"
on storage.objects
for update
to authenticated
using (bucket_id = 'card-images')
with check (bucket_id = 'card-images');

drop policy if exists "Authenticated can delete card images" on storage.objects;
create policy "Authenticated can delete card images"
on storage.objects
for delete
to authenticated
using (bucket_id = 'card-images');

-- Make the table visible to the Data API roles.
grant select on public.cards to anon, authenticated;
grant insert, update, delete on public.cards to authenticated;
