-- FRENZYGOLDIES / VAULTCARDSTR
-- Run this entire script in Supabase SQL Editor.
-- It creates the cards table, RLS policies and a public card-images bucket.

create table if not exists public.cards (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete cascade,
  player text not null,
  team text default '',
  category text not null default 'Football',
  year text default '',
  set_name text default '',
  card_number text default '',
  parallel text default 'Base',
  condition text default 'Raw',
  grade text default '—',
  price text default 'Collection',
  acquired text default '',
  rookie boolean not null default false,
  featured boolean not null default false,
  image_url text not null,
  note text default '',
  created_at timestamptz not null default now()
);

alter table public.cards enable row level security;

drop policy if exists "Public can view cards" on public.cards;
create policy "Public can view cards"
on public.cards
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated can add cards" on public.cards;
create policy "Users can add their own cards"
on public.cards
for insert
to authenticated
with check ((select auth.uid()) = owner_id);

drop policy if exists "Authenticated can edit cards" on public.cards;
create policy "Users can edit their own cards"
on public.cards
for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

drop policy if exists "Authenticated can delete cards" on public.cards;
create policy "Users can delete their own cards"
on public.cards
for delete
to authenticated
using ((select auth.uid()) = owner_id);

-- Public bucket for displaying card photos.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'card-images',
  'card-images',
  true,
  6291456,
  array['image/jpeg','image/png','image/webp']
)
on conflict (id) do update set
  public = true,
  file_size_limit = 6291456,
  allowed_mime_types = array['image/jpeg','image/png','image/webp'];

-- Public can read/download card images.
drop policy if exists "Public can view card images" on storage.objects;
create policy "Public can view card images"
on storage.objects
for select
to anon, authenticated
using (bucket_id = 'card-images');

-- Only signed-in users can upload/change/delete card images.
drop policy if exists "Authenticated can upload card images" on storage.objects;
create policy "Authenticated can upload card images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'card-images'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Authenticated can update card images" on storage.objects;
create policy "Authenticated can update card images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'card-images'
  and owner_id = (select auth.uid()::text)
)
with check (
  bucket_id = 'card-images'
  and (storage.foldername(name))[1] = (select auth.uid()::text)
);

drop policy if exists "Authenticated can delete card images" on storage.objects;
create policy "Authenticated can delete card images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'card-images'
  and owner_id = (select auth.uid()::text)
);

-- Make the table visible to the Data API roles.
revoke insert, update, delete on public.cards from anon;
grant select on public.cards to anon, authenticated;
grant insert, update, delete on public.cards to authenticated;

-- Personal Collection (PC) settings for each collector.
create table if not exists public.profile_pcs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null,
  player_name text not null,
  target integer not null default 18,
  team text default '',
  created_at timestamptz not null default now()
);

alter table public.profile_pcs enable row level security;

drop policy if exists "Public can view profile PCs" on public.profile_pcs;
create policy "Public can view profile PCs"
on public.profile_pcs
for select
to anon, authenticated
using (true);

drop policy if exists "Users can add own profile PCs" on public.profile_pcs;
create policy "Users can add own profile PCs"
on public.profile_pcs
for insert
to authenticated
with check (owner_id = auth.uid());

drop policy if exists "Users can edit own profile PCs" on public.profile_pcs;
create policy "Users can edit own profile PCs"
on public.profile_pcs
for update
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

drop policy if exists "Users can delete own profile PCs" on public.profile_pcs;
create policy "Users can delete own profile PCs"
on public.profile_pcs
for delete
to authenticated
using (owner_id = auth.uid());

create unique index if not exists profile_pcs_owner_player_unique
on public.profile_pcs (owner_id, lower(player_name));

grant select on public.profile_pcs to anon, authenticated;
grant insert, update, delete on public.profile_pcs to authenticated;



-- Security note:
-- Profiles and avatar policies are maintained in security-hardening.sql.
-- Run that migration after the initial Supabase setup.
